# This is a basic workflow to help you get started with Actions

name: Debug Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildLinux-Debug:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib haxe -y
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          sudo apt-get install vlc-bin
          sudo apt-get -y install libidn12
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-demos
          haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons.git dev
          haxelib git flixel-studio https://github.com/Dovyski/flixel-studio.git master
          haxelib install tjson
          haxelib install hxjsonast
          haxelib git hxCodec https://github.com/polybiusproxy/hxcodec
          haxelib install openfl-webm
          haxelib git SScript https://github.com/TheWorldMachinima/SScript
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib install polymod 1.5.2
          haxelib install swf 3.1.1 
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib git systools https://github.com/haya3218/systools
          haxelib install actuate
          haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Rebuild systools
        run: haxelib run lime rebuild systools linux
      - name: Compile
        run: haxelib run lime build Project.xml linux -debug --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: linuxBuild-Debug
          path: 'export/debug/linux/bin' 
  buildWindows-Debug:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-demos
          haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons.git dev
          haxelib git flixel-studio https://github.com/Dovyski/flixel-studio.git master
          haxelib install tjson
          haxelib install hxjsonast
          haxelib git hxCodec https://github.com/polybiusproxy/hxcodec
          haxelib install openfl-webm
          haxelib git SScript https://github.com/TheWorldMachinima/SScript
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib install hscript 
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib install polymod 1.5.2
          haxelib install swf 3.1.1
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git extension-webm https://github.com/KadeDev/extension-webm
          haxelib run lime rebuild extension-webm windows
          haxelib install hxcpp-debug-server
          haxelib git systools https://github.com/haya3218/systools
          haxelib install actuate
          haxelib list
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Rebuild systools
        run: haxelib run lime rebuild systools windows
      - name: Compile
        run: haxelib run lime build windows -debug --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: windowsBuild-Debug
          path: export/debug/windows/bin
  buildMac-Debug:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-demos
          haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons.git dev
          haxelib git flixel-studio https://github.com/Dovyski/flixel-studio.git master
          haxelib install tjson
          haxelib install hxjsonast
          haxelib git hxCodec https://github.com/polybiusproxy/hxcodec
          haxelib install openfl-webm
          haxelib git SScript https://github.com/TheWorldMachinima/SScript
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib install polymod 1.5.2
          haxelib install swf 3.1.1 
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git extension-webm https://github.com/KadeDev/extension-webm
          haxelib run lime rebuild extension-webm mac
          haxelib install hxcpp-debug-server
          haxelib git systools https://github.com/haya3218/systools
          haxelib install actuate
          haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Rebuild systools
        run: haxelib run lime rebuild systools mac
      - name: Compile
        run: haxelib run lime build mac -debug --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: macBuild-Debug
          path: export/debug/macos/bin
